from _typeshed import Incomplete
from ipapython.ipautil import (
    escape_seq as escape_seq,
    unescape_seq as unescape_seq,
)

unicode = str
REALM_SPLIT_RE: Incomplete
COMPONENT_SPLIT_RE: Incomplete

def parse_princ_name_and_realm(principal, realm: Incomplete | None = ...): ...
def split_principal_name(principal_name): ...

class Principal:
    components: Incomplete
    realm: Incomplete
    def __init__(
        self, components, realm: Incomplete | None = ...
    ) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
    def __hash__(self): ...
    @property
    def is_user(self): ...
    @property
    def is_enterprise(self): ...
    @property
    def is_service(self): ...
    @property
    def is_host(self): ...
    @property
    def username(self): ...
    @property
    def upn_suffix(self): ...
    @property
    def hostname(self): ...
    @property
    def service_name(self): ...
