---
# settings are provided by CI/CD pipeline or `idm-ci/secrets` source file
# Stage account settings are backed up in `ETHEL_EXPORTED_ACCOUNTS` secret.

# "prod", "stage", or "ephemeral"
rhc_env: "{{ lookup('env', 'RHC_ENV', default=undef()) }}"

# organization id and activation key
# prod: https://access.redhat.com/management/activation_keys
# stage: https://access.stage.redhat.com/management/activation_keys
rhc_org: "{{ lookup('env', 'RHC_ORG', default=undef()) }}"
rhc_key: "{{ lookup('env', 'RHC_KEY', default=undef()) }}"

# RHSM API token
# prod: https://access.redhat.com/management/api
# stage: https://access.stage.redhat.com/management/api
rh_api_token: "{{ lookup('env', 'RH_API_TOKEN', default=undef()) }}"

# COPR repo with builds (not used by hmsidm-dev.yaml)
ipa_hcc_copr: copr.devel.redhat.com/cheimes/ipa-hcc

# backend host
# oc get routes -l app=hmsidm-backend -o jsonpath='{.items[0].spec.host}'
hmsidm_backend: "{{ lookup('env', 'HMSIDM_BACKEND', default=undef()) }}"
dev_username: "{{ lookup('env', 'DEV_USERNAME', default=undef()) }}"
dev_password: "{{ lookup('env', 'DEV_PASSWORD', default=undef()) }}"

# see ipahcc.hccplatform
domain_id: '772e9618-d0f8-4bf8-bfed-d2831f63c619'
domain_token: 'mockapi'

# container registries
# Docker Hub credentials (to avoid rate limiting)
docker_username: "{{ lookup('env', 'DOCKER_USERNAME', default=undef()) }}"
docker_password: "{{ lookup('env', 'DOCKER_PASSWORD', default=undef()) }}"

backend_git_repo: "{{ lookup('env', 'BACKEND_GIT_REPO') | default('https://gitlab.cee.redhat.com/identity-management/idmocp/idm-domains-backend.git', True) }}"
backend_git_branch: "{{ lookup('env', 'BACKEND_GIT_BRANCH') | default('HEAD', True) }}"
