from _typeshed import Incomplete
from ipaplatform.paths import paths as paths

logger: Incomplete
RESOLVE1_IPA_CONF: Incomplete

class BaseTaskNamespace:
    def restore_context(self, filepath, force: bool = ...) -> None: ...
    def backup_hostname(self, fstore, statestore) -> None: ...
    def reload_systemwide_ca_store(self) -> None: ...
    def insert_ca_certs_into_systemwide_ca_store(self, ca_certs): ...
    def platform_insert_ca_certs(self, ca_certs) -> None: ...
    def remove_ca_certs_from_systemwide_ca_store(self): ...
    def platform_remove_ca_certs(self) -> None: ...
    def get_svc_list_file(self): ...
    def is_selinux_enabled(self): ...
    def check_selinux_status(self) -> None: ...
    def check_ipv6_stack_enabled(self) -> None: ...
    def detect_container(self) -> None: ...
    def restore_hostname(self, fstore, statestore) -> None: ...
    def restore_pre_ipa_client_configuration(
        self, fstore, statestore, was_sssd_installed, was_sssd_configured
    ) -> None: ...
    def set_nisdomain(self, nisdomain) -> None: ...
    def modify_nsswitch_pam_stack(
        self, sssd, mkhomedir, statestore, sudo: bool = ..., subid: bool = ...
    ) -> None: ...
    def modify_pam_to_use_krb5(self, statestore) -> None: ...
    def is_nosssd_supported(self): ...
    def is_mkhomedir_supported(self): ...
    def backup_auth_configuration(self, path) -> None: ...
    def restore_auth_configuration(self, path) -> None: ...
    def migrate_auth_configuration(self, statestore) -> None: ...
    def set_selinux_booleans(
        self, required_settings, backup_func: Incomplete | None = ...
    ) -> None: ...
    @staticmethod
    def parse_ipa_version(version): ...
    def set_hostname(self, hostname) -> None: ...
    def configure_httpd_service_ipa_conf(self) -> None: ...
    def configure_http_gssproxy_conf(self, ipauser) -> None: ...
    def remove_httpd_service_ipa_conf(self) -> None: ...
    def configure_httpd_wsgi_conf(self) -> None: ...
    def configure_httpd_protocol(self) -> None: ...
    def is_fips_enabled(self): ...
    def add_user_to_group(self, user, group) -> None: ...
    def setup_httpd_logging(self) -> None: ...
    def systemd_daemon_reload(self) -> None: ...
    def configure_dns_resolver(
        self,
        nameservers,
        searchdomains,
        *,
        resolve1_enabled: bool = ...,
        fstore: Incomplete | None = ...,
    ) -> None: ...
    def unconfigure_dns_resolver(
        self, fstore: Incomplete | None = ...
    ) -> None: ...
    def configure_pkcs11_modules(self, fstore) -> None: ...
    def restore_pkcs11_modules(self, fstore) -> None: ...
    def get_pkcs11_modules(self): ...
    def configure_nsswitch_database(
        self,
        fstore,
        database,
        services,
        preserve: bool = ...,
        append: bool = ...,
        default_value=...,
    ) -> None: ...
    def enable_sssd_sudo(self, fstore) -> None: ...
    def disable_ldap_automount(self, statestore) -> None: ...

tasks: BaseTaskNamespace
